### ISSUE TITLE
Linux black screen

### ISSUE THREAD

**Issue by hahahahaman** [yuhang174/siptag#2]
When snipping I get a black screen and then this error:

```
(node:163825) UnhandledPromiseRejectionWarning: Error: x and y must be numbers
    at Jimp.throwError (/home/demonseaman/code/siptag/node_modules/@jimp/utils/dist/index.js:33:13)
    at Jimp.blit (/home/demonseaman/code/siptag/node_modules/@jimp/plugin-blit/dist/index.js:34:34)
    at cropAndStitch (/home/demonseaman/code/siptag/main.js:240:8)
    at async desktopScreenshot (/home/demonseaman/code/siptag/main.js:266:18)
    at async IpcMainImpl.<anonymous> (/home/demonseaman/code/siptag/main.js:364:18)
(node:163825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by yuhang174** [comment]
Can you look into it?
